### ISSUE TITLE
Split phase and results into phase /phase.hyper and results / results.hyper

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#101]
Currently, once a HyperPhase runs, the results of that phase are a deepcopy of the results of the previous phase with the HyperPhase optimizer results added. I think that we should instead append the results as a hyper results instance. The API would look as follows:
```

results.from_phase('phase_1').variable.lens_galaxies.lens
results.from_phase('phase_1').hyper.variable.lens_galaxies.hyper_galaxy

```
Doing this has the following advantages:

1) We do not append new results to a previous phase's results.constant. For example, after a HyperGalaxyPhase, we add the resulting hyper galaxy's to a deep copy of the previous phase's results. This is problematic, as it means that the Result's classes properties (e.g. most_likely_fit) use this hyper_galaxy, even though the original phase never did!

2) If we use results.last, We use the actual results of the last phase, whereas now it uses the results of the last HyperGalaxyPhase. This is causing issues given point 1 above.

3) We can remove the need to give a HyperGalaxyPhase a name, using the name of the previous phase instead. This is cleaner.

4) A HyperPhase is more explicitly run, with its results stored separately. 

I next see 'HyperGalaxyPhase' becoming some general extension hyper phase, that includes all the different HyperPhase results (e.g. hyper_galaxies, pixelization, regularization, etc.)

I envision a pipeline API something like this:

```
def make_pipeline(test_name):

    phase1 = ph.LensPlanePhase(
        phase_name='phase_1', phase_folders=[test_type, test_name],
        lens_galaxies=dict(lens=gm.GalaxyModel(redshift=0.5, sersic=lp.EllipticalSersic)),
        optimizer_class=nl.MultiNest)

    phase1.optimizer.const_efficiency_mode = True
    phase1.optimizer.n_live_points = 40
    phase1.optimizer.sampling_efficiency = 0.8

    phase1.add_hyper_phase(hyper_galaxy_phase=True, hyper_pixelization_phase=True,  hyper_background_sky_phase=False)

    phase1.hyper.hyper_galaxy_phase.optimizer.const_efficiency_mode = True
    phase1.hyper.hyper_galaxy_phase.optimizer.n_live_points = 20
    phase1.hyper.hyper_galaxy_phase.optimizer.sampling_efficiency = 0.8

    phase1.hyper.hyper_pixelization_phase.optimizer.const_efficiency_mode = True
    phase1.hyper.hyper_pixelization_phase.optimizer.n_live_points = 20
    phase1.hyper.hyper_pixelization_phase.optimizer.sampling_efficiency = 0.8

    class HyperLensPlanePhase(ph.LensPlanePhase):

        def pass_priors(self, results):

            self.lens_galaxies.lens.hyper_galaxy = results.from_phase('phase_1').hyper.\
                constant.lens_galaxies.lens.hyper_galaxy

            self.lens_galaxies.lens.sersic = results.from_phase('phase_1').\
                variable.lens_galaxies.lens.sersic

    phase2 = HyperLensPlanePhase(
        phase_name='phase_2', phase_folders=[test_type, test_name],
        lens_galaxies=dict(lens=gm.GalaxyModel(redshift=0.5, sersic=lp.EllipticalSersic, hyper_galaxy=g.HyperGalaxy)),
        optimizer_class=nl.MultiNest)

    phase2.optimizer.const_efficiency_mode = True
    phase2.optimizer.n_live_points = 40
    phase2.optimizer.sampling_efficiency = 0.8

    return pl.PipelineImaging(test_name, phase1,  phase2)
```

**Comment by rhayes777** [comment]
This is because constants are just floats now. I've fixed this in AutoFit.

**Comment by rhayes777** [comment]
oops wrong issue
