### ISSUE TITLE
Move use of interpolator in potential, convergence, deflection routines to config

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#105]
Currently, we decide if a method uses the cache and interpolator based on whether I put a 

    @grids.grid_interpolate
    @geometry_profiles.cache

decorator on a method.

So, an EllipticalCoroedPowerLaw does use this method, cause it has this decorator, but an EllipticalIsothermal doesn't.

It'd be tidier if the use of this decorator was setup by a config file, for each calculation that can be done. Basically, True or False whether a method uses the interpolator.

**Comment by rhayes777** [comment]
So we would still have the decorator on each method but its behaviour could be turned on and off using config?

**Comment by Jammy2211** [comment]
Yes. At the moment, to avoid a method using it, it doesnt have the decorator. So this would also involve adding the decorator to all methods.
