### ISSUE TITLE
Make all tags configs

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#106]
Currently, tags are hardwired into the pipeline tagging module, e.g.:

```
def align_bulge_disk_axis_ratio_tag_from_align_bulge_disk_axis_ratio(align_bulge_disk_axis_ratio):
    """Generate a tag for if the bulge and disk of a bulge-disk system are aligned or not, to customize phase names \
    based on the bulge-disk model. This changes the phase name 'phase_name' as follows:

    bd_align_axis_ratio = False -> phase_name
    bd_align_axis_ratio = True -> phase_name_bd_align_axis_ratio
    """
    if not align_bulge_disk_axis_ratio:
        return ''
    elif align_bulge_disk_axis_ratio:
        return '_bd_align_axis_ratio'
```

We should make it so all tags are defined in a tagging config file, so people can name the tags themselves. The benefit of this is the directory structure of a run is more explicit to a user.

We need to be sure this won't impact the flexibility off the aggregator (I dont think it will).

**Comment by rhayes777** [comment]
How would tags be customised? What would the user input?

**Comment by Jammy2211** [comment]
I did this for pixelizaton + regularization already, so something like:

```
[tag]
fix_lens_light = fix_lens_light
Rectangular = rect
VoronoiMagnification = voro_mag
VoronoiBrightnessImage = voro_image
Constant = const
AdaptiveBrightness = adapt_bright
bin_up_factor = bin_up
sub_grid_size = sub
```

**Comment by Jammy2211** [comment]
Refactoring of tagging into the setup.py module has sorted this.
