### ISSUE TITLE
Visualisation consolidation

### ISSUE THREAD

**Issue by rhayes777** [Jammy2211/PyAutoLens#114]
Visualisation configuration is loaded in phases. This configuration could be loaded in a separate class and customised there.

For example
phase.should_plot_image_plane_pix

Could be written
phase.visual.should_plot_image_plane_pix

Meaning that all configuration loading and visualisation logic would be contained in a separate class making phases much cleaner.

Making this separation might also allow for visualisation logic to be consolidated. In particular, a single point of entry for plotting would make it much easier for users to plot.

e.g. visual.plot(my_object)

**Comment by Jammy2211** [comment]
We h ave done this with the Visualizer.
