### ISSUE TITLE
Aggregator tracer method

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#133]
Currently, we create a list of tracers from the aggregator as:

```
outputs = aggregator.filter(phase=phase_name).output

instances = [out.mp_instance for out in outputs]

tracers = [
    al.Tracer.from_galaxies(galaxies=instance.galaxies) for instance in instances
]
```

We should make a slightly neater API as

tracers = aggregator.filter(phase=phase_name).tracers

**Comment by rhayes777** [comment]
The aggregator belongs to AutoFit and as such does not know anything about Tracers or galaxies.

I've added a function that facilitates mapping of some function onto the most probable instances. For this use case it would be:

`
tracers = aggregator.map_most_probable_instance(
    lambda instance: al.Tracer.from_galaxies(
        galaxies=instance.galaxies
    )
)
`
