### ISSUE TITLE
[JOSS] Installation instructions - conda

### ISSUE THREAD

**Issue by zonca** [Jammy2211/PyAutoLens#145]
JOSS review: https://github.com/openjournals/joss-reviews/issues/2825

https://pyautolens.readthedocs.io/en/latest/general/installation.html#installation-with-conda

* I suggest to rename this section to "Installation in a conda environment", otherwise it seems there is conda package for `pyautolens`
* `anaconda` has really a lot of dependencies, I suggest to only install the largest compiled packages, for example `scipy` `astropy` `matplotlib` `numba`, and then let `pip` install the rest

**Comment by Jammy2211** [comment]
Good shouts, will update the docs accordingly :). 

Do you think we should make the conda instructions top of the installations (and the 'recommended' method) or stick to pip at the top? Both have ups and downs and it feels like we swap them round every 6 months. Newer versions of llvmlite (for numba) have made certain pip installs a pain so going back to conda seems preferable currently...

**Comment by zonca** [comment]
yes, I actually hit issues with `llvmlite` myself in one of my packages. Better recommend a `conda` environment first.

**Comment by Jammy2211** [comment]
Yep, I'm expanding the installation instructions in the docs now :), getting things up and running via a git clone / fork is worth expanding on too as I'd imagine most users will want to do this for other projects (e.g. PyAutoGalaxy) where a large chunk of lensing calculations are actually performed.
