### ISSUE TITLE
Fail in example interferometer.py

### ISSUE THREAD

**Issue by aureliocarnero** [Jammy2211/PyAutoLens#147]
Hello @Jammy2211 I'm testing the code (very nice, by the way).
Running the examples, I found an error related to interferometer.py
It claims there is a file missing (I cannot find the visibilities.fits file in the cloned repo, though)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/interferometer /mass_sie__source_sersic/visibilities.fits'

Cheers
Aurelio

**Comment by Jammy2211** [comment]
Ooooops, added to the workspace and pushed :).

The example dataset uses very low resolution interferometer data corresponding to the Square Mile Array (~300 visibilities). We're in the final stages of testing how things run for the stupidly large ALMAish datasets (> 10 million visiblities) but will hold off distributing this with the workspace (well, URL links to download the >1GB datasets from a server..) until we're sure the memory use won't crash anyone laptops :).

**Comment by aureliocarnero** [comment]
That would be great if it works for ALMA!
Thanks a lot for the quick response, I will check soon and close the issue once I have confirmed it.

**Comment by Jammy2211** [comment]
It definitely does work for ALMA! And we're prepping the docs / example scripts / whatnot atm :).

**Comment by aureliocarnero** [comment]
Cool, I tested and is working, just please remove a trailing whitespace in line 22 in interferometer.py
dataset_path = path.join("dataset", "interferometer ", dataset_name)
to:
dataset_path = path.join("dataset", "interferometer", dataset_name)

**Comment by Jammy2211** [comment]
Good spot, done :)
