### ISSUE TITLE
Modeling multiply lensed point sources with PyAutoLens

### ISSUE THREAD

**Issue by linan7788626** [Jammy2211/PyAutoLens#151]
- [ ] Include an adaptive algorithm for numerical root finding.
- [ ] Involve priors of absolute magnifications to improve the constraints on lens models.

**Comment by Jammy2211** [comment]
The algorithm for position finding is currently up and running in autolens and can be found [here](https://github.com/Jammy2211/PyAutoLens/blob/master/autolens/lens/positions_solver.py).

This is pretty efficient and works well, but needs a magnification calculation in it to remove images with low magnifications that are not observed. You sent me to the code to do that, so it should be trivial.

The main two steps that are left are the following:

Create a `FitPositions` class that given data on positions and a `Tracer` (from which model positions are computed) compares the two to compute a chi-squared and likelihood. I started working on[this a while back]https://github.com/Jammy2211/PyAutoLens/blob/master/autolens/fit/fit_positions.py) but need to finish it up. This class will support mulitple types of positional fitting (source-plane chi-squared, image-plane chisquared, etc.). I'll focus on the image-plane one for now as this is the one you actually need from what I could tell.

Finally, I need to make a `PhasePositions` class that wraps the fitting class above but the `NonLinearSearch`. This is also something I started. I'll make this a priority from here on as I know you need it asap!
