### ISSUE TITLE
Getting an AttributeError in the mass fitting code given on the GitHub page.

### ISSUE THREAD

**Issue by icantcodeman** [Jammy2211/PyAutoLens#174]
I am trying to run the code for fitting the galaxy mass given on the homepage of GitHub. I copy-pasted it but got an error saying AttributeError: 'ModelInstance' object has no attribute 'galaxies'. This error is occurring in the line: 
return ray_tracing.Tracer.from_galaxies( galaxies=instance.galaxies, cosmology=self.cosmology). Can you let me know what's the issue?

**Comment by rhayes777** [comment]
Do you mean the second example?

Would have to check with @Jammy2211 but it looks like the model is setup differently from how it's expected to be.

I think if you change the line:
```python
model = af.Collection(lens=lens_galaxy_model, source=source_galaxy_model)
```

to:
```python
model = af.Collection(galaxies=af.Collection(lens=lens_galaxy_model, source=source_galaxy_model))
```

That might fix it. If it does we'll need to update the README.

**Comment by Jammy2211** [comment]
Indeed, I believe that was the issue and using the replacement above will fix it (I have updated the Readme, albeit not pushed yet).

The README is generally not tested so errors can get through, I'd recommend you base copy-and-pasting type things with the template scripts on the autolens workspace (which are thoroughly tested before deployment and also documented more thoroughly):

https://github.com/Jammy2211/autolens_workspace/blob/release/scripts/imaging/modeling/mass_total__source_parametric.py

**Comment by icantcodeman** [comment]
First of all I'd love to thank you very much for replying so soon! I am
trying the solution that you have provided. I'll keep you updated on the
process.

**Comment by icantcodeman** [comment]
Hey there! Just wanted to let you know that your solutions worked. Also
just a random question, the fits images used in these program are for what
object?

**Comment by Jammy2211** [comment]
The majority of fits images were simulated using PyAutoLens (using the `simulator` scripts).

HST images of the lenses `slacs1430+4105` and `slacs2303+1422` are also distributed with the software (random choices based on them look pretty).

https://github.com/Jammy2211/autolens_workspace/tree/release/dataset/slacs

**Comment by icantcodeman** [comment]
Oh that is really great! Thank you for all the information and quick
replies again. I am using this for a college project.
