### ISSUE TITLE
Dude about how to translate the results from pyautolens to lenstronomy for basic modeling.

### ISSUE THREAD

**Issue by felavila** [Jammy2211/PyAutoLens#176]
Hi, when i use tracer = al.Tracer.from_galaxies(galaxies=[mp_instance.galaxies,lens_0.mass,],mp_instance.galaxies.source), then fit=al.FitPointDict(point_dict=point_dict, tracer=tracer, positions_solver=solver), next  fit["point_0"].positions.model_positions, the positions are the produced by the model?, if they are i would like to reproduce these images in lenstronomy for reason i am getting the parameters from mp_instance.galaxies,lens_0.mass.angle for example and putting in lenstronomy script and i am not getting the same images for that reason i would like also know if i have to do some process. I hope you can understand my question and sorry for my bad english. Cheers 
Felipe Avila 
Master degree studentUniversidad de Valparaiso

**Comment by Jammy2211** [comment]
I am not 100% sure what you asking, but (assumingy you have a `result` which you use are using to get `mp_instance`) you could try:

```
tracer = result.max_log_likelihood_tracer
fit = al.FitPointDict(point_dict=point_dict, tracer=tracer, positions_solver=solver)
fit["point_0"].positions.model_positions
```

This should give you the positions from the model.

**Comment by Jammy2211** [comment]
I honestly have no idea.

It is highly like that autolens and lenstronomy adopt different conventions for parameters. Especially something like `angle`, which could be defined from the x axis or y axis in the clockwise or counter clockwise direction.

I doubt I can provide much more help!
