### ISSUE TITLE
Voronoi Interpolation 

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#181]
Using MetPy (https://unidata.github.io/MetPy/latest/examples/gridding/Natural_Neighbor_Verification.html) Qiuhan has demonstrated that we can compute interpolation weights for a Voronoi mesh and feed this through to the `mapping_matrix`.

However, the implementation leads to a x20 slow down compared to PyAutoLens's non-interpolated Voronoi mesh.

**Interpolation Algorithm**

First, we need to determine if there is a solution which can compute the natural neighbor interpolation scheme of a Voronoi mesh in comparable run times to autolens's existing implementation. The only feasible route currently seems to be trying to speed up MetPy, via numba.

If there is no fast implmentation, we should still implement this using the slow natural neighbor routines in MetPy, but accpet that this will probably only be used for testing / investigating as opposed to full blown lens modeling.

**PyAutoLens Implementation**

We essentially need to write a function which, via MetPy, outputs the 3 arrays described in the issue https://github.com/Jammy2211/PyAutoLens/issues/180 (`pixelization_indexes_for_sub_slim_index`, `pixelization_interpolation_weights`, `pixelization_interpolation_sizes`).

**Comment by qiuhan96** [comment]
Just tested how much Numba would accelerate the natural neighboring computation.
For 125000 sub pixels and 5000 source pixels the time for pairing is ~ 1.2s, while time cost for weights computing is ~ 20 s

When Numba is set off, the time for paring is ~ 1.3s, while time cost for weights computing is ~ 170 s.

There is still a certain distance in speed even using Numba.

**Comment by Jammy2211** [comment]
I think that will still prove useable and is worth implementing, albeit in limited settings. For example, even if its too slow for modeling, it might be useful to have for simulating images from the source reconstruction.

For annular masks the number of subpixels will be more like ~30000 and the source pixels could go well below 2000, at which point the run times probably become good enough for modeling.

It seems highly like we'll be switching to Delaunay grids though, as standard, provided they are not out performed by Voronoi.

**Comment by qiuhan96** [comment]
I will think more about the code. I feel it shouldn't be slow, since actually not many complicated things done in weights computing.

**Comment by Jammy2211** [comment]
We implemented a C algorithm which makes it fast.
