### ISSUE TITLE
Delaunay Implementation

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#183]
We are going to implement a Delaunay source reconstruction.

This issue provides a step-by-step breakdown of how to do this (it ignores source plane interpolation for now and simply aims to implement a Delaunay that does not use source plane interpolation):

**Step 1: Pixelization Grid**

The package https://github.com/Jammy2211/PyAutoArray/blob/master/autoarray/structures/grids/two_d/grid_2d_pixelization.py implements 2D grids which are tied to a specific geometric mesh. It currently implements a `Grid2DRectangular` and `Grid2DVoronoi`. 

We first need to create a `Grid2DDelaunay` as follows:

- There are a number of `property`s which make it straight forward to visualize each grid in `matplotlib`, for example `extent`, `scaled_maxima`. The Delaunay needs the same properties as the Voronoi grid, thus we can create an absttract class above them (e.g. `Grid2DIrregularMesh` where these properties are shared.

- The `Grid2DVoronoi` has a property `voronoi` which creates the mesh via SciPy. We need to write an equivalent property for the Delaunay.

- The property `pixel_neighbors` creates an ndarray describing the neighbors of every source pixel. The Rectangular and Voronoi grid have their own specific functions to do this, and we will need to write one specific to the Delaunay.

**Step 2: Pixelization**

The package https://github.com/Jammy2211/PyAutoArray/tree/master/autoarray/inversion/pixelizations implements the `Pixelizations` as models which are what we call when we perform lens modeling.

For the Delaunay grid, we can essentially just copy and paste the module `voronoi.py` and update the `make_pixelization_grid()` function to use the `Grid2DDelaunay` above, alongside having `mapper_from()` return a `MapperDelaunay`. 

This will give us `DelaunayMagnification` and `DelaunayBrightnessImage` objects.

**Step 3: Mapper**

The package https://github.com/Jammy2211/PyAutoArray/tree/master/autoarray/inversion/mappers implements `Mapper` objects, which given a source-plane pixelization and mapped image-pixel sub-pixels determines the mappings between the two (which are then used to perform an inversion).

We can essentially copy and paste the `MapperVoronoi` object to create a `MapperDelaunay` object. We can even reuse the function that Voronoi calls to compute `pixelization_index_for_sub_slim_index`, which pairs image sub pixels to source pixels.

NOTE: Currently, the `MapperDelaunay` object is a near carbon copy of the `MapperVoronoi` object, which could motivate use combining them into a `MapperIrregularMesh` object. However, the implementation that we decide in issue https://github.com/Jammy2211/PyAutoLens/issues/182 may mean that the Delaunay implements a few unique functions, so let us keep them separate for now.

**Step 4: Configs**

The `DelaunayMagnification` and `DelaunayBrightnessImage` objects are model-components, thus they need priors to be included in the following **PyAutoGalaxy** module:

https://github.com/Jammy2211/PyAutoGalaxy/blob/master/autogalaxy/config/priors/pixelizations.json

**Comment by qiuhan96** [comment]
Just out of curiosity on the Step 1's pixelization_neighbors: For a given set of points, should the neighbors defined in the Voronoi term (polygons sharing edges) be the same as the neighbors defined in the Delaunay term (triangles sharing edges)?

For Delaunay, I currently compute the neighbors using this built-in function:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.vertex_neighbor_vertices.html#scipy.spatial.Delaunay.vertex_neighbor_vertices

It returns a maximum number of neighbors of 9, which is the same as the maximum number of neighbors of a Voronoi tessellation.

**Comment by Jammy2211** [comment]
I would have expected the maximum neighbors of a Delaunay triangulation to be 3, corresponding to the 3 triangle edges of each pixel. 

Do you know what the 9 corresponds too? And if its related to the Vornoi grid does it vary depending on the source pixelization (as I would guess Voronoi cells can have more / less than 9).

**Comment by qiuhan96** [comment]
![Selection_553](https://user-images.githubusercontent.com/48360053/145386696-57f93ebe-8b71-4041-8f43-da5b3370bf26.png)

**Comment by qiuhan96** [comment]
This is an example of Delaunay tessellation. The black points are the traced back pixels and the white points are the circumcentres of the triangles. In Delaunay tessellation, a black point (traced pixel grid) is not associated with only one triangle, instead, it can be a vertice of many triangles. In that sense, it should have more than three neighbors. For example, the black point in the center has 7 neighbors since it connects to 7 other black points.

**Comment by qiuhan96** [comment]
![image](https://user-images.githubusercontent.com/48360053/145387548-89c957db-7e12-4407-98f3-56886a96552f.png) (from https://gwlucastrig.github.io/TinfourDocs/NaturalNeighborTinfourAlgorithm/index.html)

Or this image shows it better. Seems Voronoi neighbors are the same things as the Delaunay neighbors.

**Comment by Jammy2211** [comment]
Does a image-pixel source-pixel pairing every have more than 3 interpolations?

**Comment by qiuhan96** [comment]
No. An image-pixel source-pixel pairing only has 3 interpolations.

**Comment by Jammy2211** [comment]
Okay, great. That plays a signifcantly role in the run times of the linear algebra (especially for w-tilde) so is a relief.

**Comment by qiuhan96** [comment]
I will check it
