### ISSUE TITLE
priors module - hypercube vector swaps entries

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#19]
The reconstruction_for_vector in the priors module works perfectly, assigning physical values from a unit hypercube as expected to setup a reconstruction class. This includes for cases where the priors are updated after being loaded from the config file or set equal to one another - I've added tests showing this.

However, the value_vector_for_hypercube_vector still swaps the physical values that are output, if the priors are either updated manually after the initial set up or set equal to one another. This is still problematic, as the unit hypercube and physical hypercube must maintain the same order. I have added a unit test showing the problem, which I've pasted below:

```
        def test__order_maintained_with_prior_change(self):

            collection = prior.ClassMap(
                prior.Config(config_folder_path=data_path+"config_test"),
                profile_1=geometry_profiles.EllipticalProfile, profile_2=geometry_profiles.Profile,
                profile_3=geometry_profiles.EllipticalProfile)

            collection.profile_1.axis_ratio = prior.UniformPrior(100, 200)

            assert collection.value_vector_for_hypercube_vector([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]) == \
                   [150.0, 0.8, 0.5, 0.25, 0.5, 0.25, 0.75, 0.8, 0.5, 0.25]
```

The error is that the 150.0 entry does not appear first in the output list, but last.

I am confident I have the tools I need to fix this myself - infact I have already hacked together a solution (in the CTI code) which addresses cases like the one above - by moving the physical values to their correct entries in the list. I haven't yet solved this for settings priors equal to one another (e.g.  collection.profile_1.axis_ratio =  collection.profile_2.axis_ratio )

**Comment by Jammy2211** [comment]
Ok, I will expand on this a bit - there are commented out tests in test_priors that show the behaviour. Once you're back, we'll have MultiNest properly up and running so it'll be clearer what we want from the the priors module.

If we setup a model via the .ini file, its priors are ordered as the constructor's input parameters. This is ideal, and means things are working before we attempt to change a prior.

Problems arise when we edit priors, either through a command like model.param1 = UniformPrior(0.0, 1.0) or model.param1 = model2.param4. These don't maintain the order of the class constructor, leading to two problems:

- The order of the unit_hypercube vector is muddled, meaning the MultiNest output files will change the order of their parameters is fairly arbritrary ways. 

- The corresponding Recon functions lose their ordering.

Furthermore, just to mess with you more, the Galaxy module doesn't play nice with the priors module either.

**Comment by Jammy2211** [comment]
NOTE: I have swapped the line below such that the tuple priors come first:

    @property
    def priors(self):
        return [prior for tuple_prior in self.tuple_priors for prior in tuple_prior[1].priors] + self.direct_priors

This means that centre (which is now defined as every models first parameter) always come first when loading classes for priors. This will allow me to setup some MultiNest interface routines.

However, this means that if a model has a tuple which is after a float, these routines won't work.

**Comment by rhayes777** [comment]
So ordering won't matter for the class constructors provided that priors are named properly. When key word arguments are passed into a constructor the order doesn't matter. What the ** operator applied to a dictionary does is unpack it's contents as key value pairs that can be passed to a constructor as key word arguments.

Priors won't work with a galaxy as it's built to instantiate classes that only require float or tuple arguments in their constructor. A galaxy is a higher level class that comprises other classes. If it makes sense to we could create some galaxy specific extension of the priors module but it depends on how priors is used in the pipeline.

Is misordered physical quantities still an issue? I can take a look if it is.

**Comment by Jammy2211** [comment]
Which Python are you referring to all this in? Python 3.6 changes dictionaries to being ordered, and therefore the unit tests change behaviour for python 2.7 and 3.6. I've commented out unit tests that show the desired behaviour but don't work (in Python 3.6, and 2.7 I think). Its basically when you change priors after using the ClassMap issues arise.

Ideally, we'd be able to apply the priors module on the GalaxyCollection class (which I've now renamed the RayTracingPlane class), in a way that incorporates all instances of the Galaxy class it contains. This would include making certain Galaxy properties free parameters to model (e.g. the redshift), if we feel like it (although normally we'd just want to model the mass / light profiles / source reconstruction).

The way I think is most intuitive to code is if someone can literally just use the RayTracingPlane to setup the lens ssystem e.g.:

lens_galaxy_1 = Galaxy(redshift=0.5, light_profiles=[EllipticalSersicLightProfile, EllipticalExponentialLightProfile], mass_profiles=[EllipticalPowerLawMassProfile])

lens_galaxy_2 = Galaxy(redshift=0.5, light_profiles=[EllipticalSersicLightProfile], mass_profiles=[EllipticalIsothermalMassProfile])

source_galaxy = Galaxy(redshift=0.5, light_profiles=[AmorphousSourcePixelization], mass_profiles=None)

ray_tracing = RayTracingPlane(galaxies=[lens_galaxy_1, lens_galaxy_2, source_galaxy])

model = SuperMap(ray_tracing)

Where SuperMap is what we call Class map... but Super magical. This might be a bit over the top for what needs coding, so let us know what you think...

**Comment by Jammy2211** [comment]
I would also point you to issue https://github.com/Jammy2211/PyAutoLens/issues/18, for how I'm using the ClassMap for visualization. I think that ClassMap should operate exclusively on RayTracingPlane - there is no circumstance where we'd want to model just a lens galaxy, or just a certain light profile (and if there is, we can just set it up as a RayTracingPlane, or create another 'super-class' analogous to RayTracingPlane). 

So yeah, if possible, everything that is part of the constructors of the classes in the RayTracingPlane class should have the option to be a free parameter. We can use config files to default these parameters to sensible values / behaviour. 

The only thing I need to think about now are hyper-parameters. Source-plane hyper parameters are easy, as they will be in the constructor of the source-plane classes and thus incorporated into RayTracingPlane via the light_profile constructors. However, there are hyper-parametes associated with scaling the observed image. I guess we add another input variable to the RayTracingPlane class like 'image_scaling'.

**Comment by rhayes777** [comment]
ade1451a735619f6fd569b08239028f6220101b1 resolves the issue of disordered results. The function "physical_values_ordered_by_class" returns a list of physical values ordered by class name and attribute name. Note that if two PriorModels share a Prior then the length of the physical_values vector will be longer than the input unit_vector because one resulting value will be returned twice, once for each PriorModel with which the share Prior is associated.

These changes do not mean that the input unit hypercube vector retains the same order. When a new prior is created then the last value in the hypercube vector will be passed to that prior. Any prior creation should happen before multinest is used in conjunction with the priors module such that the length and ordering of the required unit hypercube vector never changes.

**Comment by Jammy2211** [comment]
Priors / Model mapper are a lot more smart now ;)
