### ISSUE TITLE
scipy.spatial.KMeans doesn't support weighted clustering

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#2]
To adapt to the source's morphology, we need to cluster source pixels in its brightest regions but weighting the clustering to its brighter pixels. In Fortran, this used a weighted k-means algorithm, which Python doesn't appear to support.

We either need to find another algorithm, or come up with an approach that addresses this by removing faint pixels from the vector of points fed into the KMeans, thus making similiar behaviour. This approach is appealing in that it will greatly speed up the KMeans clustering, if it works as it should.

**Comment by rhayes777** [comment]
David mentioned Density Bases Spatial Clustering:

https://en.wikipedia.org/wiki/DBSCAN

It's supported by sklearn:

http://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html

It supports weights so it should be applicable.

**Comment by Jammy2211** [comment]
interesting. DBSCAN seems different to k-means and would probably change the behaviour of source-plane clustering in a non-trivial way, for better or worse. I'm eager to implement it for fun, but I'm not sure it can replace KMeans. For example, it doesn't take a specified number of source-pixels (clusters) to derive the source-plane.

Reading around, it sounds like if we want to use vanilla sklearn.KMeans we'll have to come up with a few routines which add points in high-weighted areas and / or remove them from low-weighted areas, which is a bit messy.

**Comment by Jammy2211** [comment]
Thinking about it more, the approach of adding / removing points just won't work in a standardizable way, and could be very slow.

https://github.com/scikit-learn/scikit-learn/pull/4218

That is a branch someone made which support KMeans with weighting. Can we nab that somehow? (even if it involves just taking the source code :/).

We definitely need a weighted K-Means so this is a potential stumbling block.

**Comment by Jammy2211** [comment]
Ok, I've come up with a scheme for how we can circumvent a lack of weighted k-means, if necessary. This will probably sound like gibberish, and is more so that I don't forget it.

We don't have to feed KMeans all the coordinates that we want it to cluster. Instead, we can extract a sub-set of coordinates to feed KMeans and use the resulting clusters to match the other coordinates we omitted. Indeed, this is already what our 'sparse' coordinates do, by turning the image-plane pixels into a coarser (but still uniform) grid of sparse image-pixels, which are the only ones fed to KMeans. 

We could develop a scheme where this sub-set of sparse image-pixels are extracted in a way which uses their weights, such that pixels with higher weights are preferentially extracted (and visa versa). This could be done by:

- Careful 2D surface fitting of the weight-map, drawing points from its surface in a 'uniform' way.
- Randomly drawing image-pixels, with this random sampling tuned to their weights (I fear this will add noise though, so the above approach seems a lot more sensible).

Benefits:

This could significantly reduce the number of sparse pixels that are used by KMeans, thereby speeding up the k-means clustering a lot. This alone makes me tempted to try it, as clustering is one of the 3 key bottlenecks.

Could use this approach to build light-adaptive Delaunay grids, which'd be fun.

Drawbacks:

The surface-fitting step could be slow. We'll have some wiggle-room is how we set this up though, and it is fixed for the majority of the pipeline anyway.

**Comment by rhayes777** [comment]
How would we perform the subsetting? 

On your other point, we could install the code as it stands at that pull request:

https://stackoverflow.com/questions/13561618/pip-how-to-install-a-git-pull-request <https://stackoverflow.com/questions/13561618/pip-how-to-install-a-git-pull-request>

The pull request was made in 2015. It looks like somebody needs to fix the merge conflicts; seems a shame they haven’t got round to it?

**Comment by Jammy2211** [comment]
Yeah, its a real shame, looks like they gave up. We can get by for now with ordinary KMeans (this can be used in the initial stages of the analysis anyway so is worthwhile implementing).

The subsetting I don't know, its not a trivial task. The idea is we have a 2d array of weights, and in some uniform and regular way want to draw a number of samples (i.e. 5000 from 50000 image pixels) from that 2D array. One could fit a 2D model to the weight array and draw points from that analytically but it sounds like it could be quite computationally expensive. 

I'll keep thinking about it - even if we managed to get a weighted kmeans im keen to try this approach too as we could do some really cool Delaunay triangulation source pixelizations.

**Comment by rhayes777** [comment]
It depends on how the points are stored. If we had an ordered list of coordinate pairs then taking every second or third coordinate pair would be trivial.

**Comment by rhayes777** [comment]
Fast K-Means library with weighted clustering example:

https://github.com/siddheshk/Faster-Kmeans

**Comment by Jammy2211** [comment]
We could compute the weight of every pixel as a value between 0 and 1 (which is what we do for weighted kmeans anyway) and then remove all points by compairing to random numbers generated between 0 and 1. This would potentially be very fast, but could also be very stochastic.

Seeding the RNG would ensure a smooth, less noisy likelihood surface

**Comment by Jammy2211** [comment]
It now does, as of mid 2018 :) (I dont know how we missed this).
