### ISSUE TITLE
scipy.integrate Requires LowLevelCallable

### ISSUE THREAD

**Issue by rhayes777** [Jammy2211/PyAutoLens#3]
Integration using functions such as quad raises the warning that the function argument should be a low level callable. e.g. in line 157 of mass_profile.py:

`potential = quad(self.potential_func, a=0.0, b=1.0, args=(coordinates,))[0]`

self.potential function should be a LowLevelCallable.

The docs describe [how a compiled c function can be used in this respect](https://github.com/scipy/scipy/blob/master/doc/source/tutorial/integrate.rst#faster-integration-using-low-level-callback-functions).

However, SciPy supports [using python functions written in a very particular as LowLevelCallables](https://ilovesymposia.com/2017/03/12/scipys-new-lowlevelcallable-is-a-game-changer/).

Ideally all deflection functions should be modified or duplicated to be used as LowLevelCallables.

This would make calling these functions confusing. It may make sense to define any function to be used in integration as an inner function of the function that performs the integration.

**Comment by Jammy2211** [comment]
https://github.com/Jammy2211/PyAutoLens/issues/16

If we use the 1D deflection approach listed in that issue, we can do away with the quad function and circumvent the need to use a LowLevelCallable.

**Comment by Jammy2211** [comment]
We use Cython + GSL integration to do this now.
