### ISSUE TITLE
`PointSolver` option to return two image positions

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#314]
One use case for the `PointSolver` is it provides us with the multiple image positions for lens modeling, which are used to prevent the mass model from going to unphyiscal solutions where the images don't trace near one another.

This works in most use cases, but I am modeling a lens which is effectively a singly imaged but nearly strong lens system:

![image](https://github.com/user-attachments/assets/7b50447f-f1ec-4368-bd2c-5952a6506856)

This means the `PointSolver`, correctly, only identifies one multiple image that traces within the source (the bright spot to the north of the centre).

However, for lens modeling I still want a counter image / multiple position on the other side of the arc, which will prevent my lens modeling from going to unphyiscal solutions. 

There must be a region of the image plane to the south of the arc which goes near the source-plane centre, but whose triangle does not quite contain the source.

Would it be possible to have an option which by default is off, but if its on it also includes the image-plane positions of the nearest source plane triangle to the source centre which is not contiguous with the triangle that actually contains the source? So in the example above, would return an image position towards the south of the lens.

**Comment by Jammy2211** [comment]
This should only be activated when 1 image position is returned by `solve`.

**Comment by rhayes777** [comment]
It would be really straightforward to do the three nearest if that's useful?

**Comment by Jammy2211** [comment]
Yeah, I understand we want to avoid this being a complex implementation.

Are you able to do the 3 points of the N nests of neigbors, so:

- if N = 0 (or None) the algorithm behaves as normal.
- If N = 1, it returns the 3 nearest.
- If N = 2, it returns the 3 nearest AND the 3 nearest of each of those.

I can then work out from there what I need to get the image positions necessary for lens modeling.

**Comment by rhayes777** [comment]
N=2 as 9 triangles would be easy

**Comment by Jammy2211** [comment]
Ok, implement N=2

**Comment by Jammy2211** [comment]
So, I essentially have a test case that indicates something going wrong with the solver, which I thought this issue would fix but it does not.

Here is an image of the lens I fitted:

![image](https://github.com/user-attachments/assets/5377d5a9-5b30-4d55-bedd-a5db207a92f9)

The image shows that there is a significant arc to the north, and a faint counter image to the south.

The code then uses the solver to find the multiple images of this lens system, however it only finds two images with the following coordinates:

```
Grid2DIrregular([[-0.1425    , -0.00442034],
       [-0.14328125, -0.00442034]])
```

Here is an image with those coordinates plotted:

![image](https://github.com/user-attachments/assets/de67dafb-94a1-43a4-8861-c2927193e7b8)

Here is a standalone Python script which reproduces all inputs and outputs the images above:

```
import autolens as al

mass = al.mp.Isothermal(
    centre=(0.0, 0.0),
    ell_comps=(0.015965431217672174, -0.4556443832314783),
    einstein_radius=0.63088748602856,
)

shear = al.mp.ExternalShear(gamma_1=-0.00727995095597, gamma_2=-0.08634963699306)

mass_extra_0 = al.mp.IsothermalSph(
    centre=( 1.95, -1.25),
    einstein_radius=0.06043414075696
)

mass_extra_1 = al.mp.IsothermalSph(
    centre=(-2.05, -0.25),
    einstein_radius=0.0573662939881,
)

galaxy_0 = al.Galaxy(
    redshift=0.5,
    mass=mass,
    shear=shear,
)

galaxy_1 = al.Galaxy(
    redshift=0.5,
    mass=mass_extra_0,
)

galaxy_2 = al.Galaxy(
    redshift=0.5,
    mass=mass_extra_1,
)

tracer = al.Tracer(galaxies=[galaxy_0, galaxy_1, galaxy_2, al.Galaxy(redshift=1.0)])

grid = al.Grid2D.uniform(shape_native=(100, 100), pixel_scales=0.1)

solver = al.PointSolver.for_grid(
    grid=grid,
    pixel_scale_precision=0.001,
)

multiple_images = solver.solve(
    tracer=tracer,
    source_plane_coordinate=(0.2919590727663824, -0.03519400014188682)
)

print(multiple_images)
```

For a while I thought the issue might be that the source centre is technically outside all caustics and therefore is singly imaged, and that the code is in a sense behaving as expected. However, with the code extract above if I change the line `source_plane_coordinate=(0.2919590727663824, -0.03519400014188682)` by small values I do not recover multiple distinct images.

It feels like there must be some sort of edge case or behaviour breaking the solver.

**Comment by Jammy2211** [comment]
Ok, so on the branch `feature/coordinate_array_main` unit tests are broken and there is clearly something broken with the solver, explaining the behaviour above.

If I switch to `main`, I get the correct positions from the extract above:

```
Grid2DIrregular([[-0.14273183, -0.004375  ],
       [ 0.64859888, -0.51625   ]])
```

So, the good news is the solver is fine and the issue I described above is some sort of weird one-off probably associated with the `neihgbor` input.

Maybe we need a call in case what this input should do was miscommunicated, but I think it breaks _everything_ so is implemented incorrectly.
