### ISSUE TITLE
Spherical models use EllipticalProfile Geometry

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#36]
All Spherical profiles inherit from their elliptical counterpart. This means that they don't use the SphericalProfile transform grid function, which is faster than the EllipitcalProfile equivalent.

We should change our inheritance structure to address this and add unit tests testing the inheritance

**Comment by rhayes777** [comment]
The elliptical transforms now check the name of the class and use the super spherical method if the class name starts with "Spherical"
