### ISSUE TITLE
Factory for setting up Phases

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#37]
The interface will have the following three Phase's for the user to choose from:

LensPlanePhase - Only a lens plane, with lens_galaxies, is included - this is used purely for fitting the foreground objects with a light profile (i.e. no mass-profiles / deflection angles).

LensSourcePlanePhase - A lens and source plane phase, thus including lens and source galaxies. This is used for 99% of use cases where everything is treated on just two planes. The source-galaxy can have a pixelization or use light profiles.

MultiPlanePhase - An arbritrary number of planes, where each is composed on galaxies with light, mass and / or pixelizations. This phase will be integrated into AutoLens in a few months, once we're sure the above two are optimal.

However, the phase module itself will have many child phases, which are sub-sets of the above phases but specify whether the lens and source-plane use light-profiles or pixelizations to model the light. They also include hyper-parameters optimization phases and specify what is visualized. By my count, we need the following child phases:

- LensPhase - As LensPlanePhase above.

- LensHyperPhase - Use the lens galaxy light profiles fitted in LensPlanePhase to setup the HyperGalaxy of each galaxy.

- LensMassOnlySourceProfilePhase - The lens galaxy has no light profile (mass-profile only). The source uses light profiles.

- LensMassOnlySourceProfileHyperPhase - Use the source-galaxy light profile above to setup a HyperGalaxy.

- LensMassOnlySourcePixelizationPhase - The lens galaxy has no light profile (mass-profile only). The source uses a pixelization.

- LensMassOnlySourcePixelizationHyperPhase - Use the source-galaxy pixelization above to setup a HyperGalaxy and the pixelization's adaptive regularization / tesselation hyper-parameters.

- LensProfileSourceProfilePhase - The lens galaxy has light and mass profiles. The source uses light profiles.

- LensProfileSourceProfileHyperPhase - Use the source-galaxy light profile above to setup a HyperGalaxy.

- LensProfileSourcePixelizationPhase - The lens galaxy has light and mass profiles. The source uses a pixelization.

- LensProfileSourcePixelizationHyperPhase - Use the source-galaxy pixelization above to setup a HyperGalaxy and the pixelization's adaptive regularization / tesselation hyper-parameters.

Lets worry about child-phases of MultiPlanePhase later, once we have a clear idea of how the phase module looks above. Multi-planes will also care about whether profiles and pixelization are used.

**Comment by rhayes777** [comment]
Do all of these phases call fitter in a different way?

It may be helpful to display this information in a table

**Comment by Jammy2211** [comment]
LensPhase:  
```
tracer = ray_tracing.TracerImagePlane(lens_galaxies=instance.lens_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.ProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood
```

LensHyperPhase: 
```
tracer = ray_tracing.TracerImagePlane(lens_galaxies=instance.lens_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.HyperProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
return ffitter.likelihood
```

LensMassOnlySourceProfilePhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.ProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood
```

LensMassOnlySourceProfileHyperPhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.HyperProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood
```

LensMassOnlySourcePixelizationPhase :
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
 fitter = fitting.PixelizationFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood
```

LensMassOnlySourcePixelizationHyperPhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.HyperPixelizationFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood

```
LensMassOnlySourcePixelizationHyperPhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.ProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood
```

LensProfileSourceProfileHyperPhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.HyperProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
return fitter.likelihood
```

LensProfileSourcePixelizationPhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.ProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
fitter = fitter.pixelization_fitter_with_profile_subtracted_lensing_image(lensing_image=self.lensing_image)
return fitter.likelihood
```

LensProfileSourcePixelizationHyperPhase: 
```
tracer = ray_tracing.TracerImageSourcePlanes(lens_galaxies=instance.lens_galaxies, source_galaxies=instance.source_galaxies, image_grids=self.lensing_image.grids)
fitter = fitting.HyperProfileFitter(lensing_image=self.lensing_image, tracer=tracer)
fitter = fitter.pixelization_fitter_with_profile_subtracted_lensing_image(lensing_image=self.lensing_image)
return fitter.likelihood
```

**Comment by Jammy2211** [comment]
I set out of refactor the fittting module, and essentially ended up implementing this factory there, where it makes a lot more sense in all honesty.

**Comment by Jammy2211** [comment]
We are definitely at the point where this factory has been implemented in the fitting module, so issue closed
