### ISSUE TITLE
Add galaxy index to paramnames

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#40]
Currently, the paramnames use lens_galaxies or source_galaxies, but without an index, e.g:

lens_galaxies_centre_0                            x_{\mathrm{geometry_profile11}}
lens_galaxies_centre_1                            y_{\mathrm{geometry_profile11}}
lens_galaxies_axis_ratio                          q_{\mathrm{geometry_profile11}}
lens_galaxies_phi                                 phi_{\mathrm{geometry_profile11}}
lens_galaxies_intensity                           I_{\mathrm{geometry_profile11}}
lens_galaxies_effective_radius                    R_{\mathrm{geometry_profile11}}
lens_galaxies_sersic_index                        n_{\mathrm{geometry_profile11}}

The problem is that if we have two lens galaxies with repeated entries, we get duplicate paramnames, e.g.:

lens_galaxies_centre_0                            x_{\mathrm{geometry_profile11}}
lens_galaxies_centre_1                            y_{\mathrm{geometry_profile11}}
lens_galaxies_axis_ratio                          q_{\mathrm{geometry_profile11}}
lens_galaxies_phi                                 phi_{\mathrm{geometry_profile11}}
lens_galaxies_intensity                           I_{\mathrm{geometry_profile11}}
lens_galaxies_effective_radius                    R_{\mathrm{geometry_profile11}}
lens_galaxies_sersic_index                        n_{\mathrm{geometry_profile11}}
lens_galaxies_centre_0                            x_{\mathrm{geometry_profile11}}
lens_galaxies_centre_1                            y_{\mathrm{geometry_profile11}}
lens_galaxies_axis_ratio                          q_{\mathrm{geometry_profile11}}
lens_galaxies_phi                                 phi_{\mathrm{geometry_profile11}}
lens_galaxies_intensity                           I_{\mathrm{geometry_profile11}}
lens_galaxies_effective_radius                    R_{\mathrm{geometry_profile11}}
lens_galaxies_sersic_index                        n_{\mathrm{geometry_profile11}}

This causes problems with GetDist and leads to an error. So lets add an index to the paramnames:

lens_galaxies_0_centre_0                            x_{\mathrm{geometry_profile11}}
lens_galaxies_0_centre_1                            y_{\mathrm{geometry_profile11}}
lens_galaxies_0_axis_ratio                          q_{\mathrm{geometry_profile11}}
lens_galaxies_0_phi                                 phi_{\mathrm{geometry_profile11}}
lens_galaxies_0_intensity                           I_{\mathrm{geometry_profile11}}
lens_galaxies_0_effective_radius                    R_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic_index                        n_{\mathrm{geometry_profile11}}
lens_galaxies_1_centre_0                            x_{\mathrm{geometry_profile11}}
lens_galaxies_1_centre_1                            y_{\mathrm{geometry_profile11}}
lens_galaxies_1_axis_ratio                          q_{\mathrm{geometry_profile11}}
lens_galaxies_1_phi                                 phi_{\mathrm{geometry_profile11}}
lens_galaxies_1_intensity                           I_{\mathrm{geometry_profile11}}
lens_galaxies_1_effective_radius                    R_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic_index                        n_{\mathrm{geometry_profile11}}

**Comment by Jammy2211** [comment]
This problem also occurs if a galaxy has the same profile twice. Thus, we should also icnlude the profile label in the tag, e.g.:

For something like

`    phase1 = MMPhase(lens_galaxies=[gp.GalaxyModel(sersic0=lp.EllipticalSersic),
                                    gp.GalaxyModel(sersic1=lp.EllipticalSersic)],`

We should get 

lens_galaxies_0_centre_0 x_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic0_centre_1 y_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic0_axis_ratio q_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic0_phi phi_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic0_intensity I_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic0_effective_radius R_{\mathrm{geometry_profile11}}
lens_galaxies_0_sersic0_sersic_index n_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_centre_0 x_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_centre_1 y_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_axis_ratio q_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_phi phi_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_intensity I_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_effective_radius R_{\mathrm{geometry_profile11}}
lens_galaxies_1_sersic1_sersic_index n_{\mathrm{geometry_profile11}}


The constant_x2_profile and constant_x2_galaxy model_mapper integration tests now show this behaviour

**Comment by rhayes777** [comment]
The name or position in the list of a each galaxy is now included in paramnames output
