### ISSUE TITLE
Automatic Prior Linking

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#44]
Currently, one has to always manually pass the priors between two phases. This is good in that it provides full customization of the modeling, but has to major downsides:

1)  Writing pipelines is cumbersome, because you have to specify how every prior links together.
2) It is not possible to link two models with different parametrizations (i.e. going from a SIE with einstein_radius as its normalization to an NFW which has kappa_s as its normalization).

I want us to aim for an automated prior linking scheme, whereby the 'pass_priors' function becomes as 'overwrite_priors' function such that users have some sense of how priors have automatically linked. Its bold, and a little bit crazy, but I believe it can work.

The first issue we need to address, is how do we tie two profiles together with two different parametrizations? This can be performed by pairing them based on their integrated quantities, for example, their luminosity and mass within an aperture.

For example, lets say we have an SIE mass profile, and we compute its mass within 1" is 10 mass units. We can go to the NFW mass profile we're linking it to, and ask, 'what value of kappa_s gives us 10 mass units in an aperture of 1"'. If we have two parameters that control mass, we can do this on a 2D grid. If we have 5 parameters, we can set-off a quick downhill simplex or MultiNest search to find the combination of 5 parameters that give 10 mass units in 1".  In Implementation, lets always just use a non-linear search like MultiNest, it'll be easier.

The parameters we infer thus link two mass models. They can be used as Gaussian priors in the next phase. The sigma's on these priors can use the priors/width config files.

For light profiles, we can play the exact same game with luminosity.

Geometric parameters should not be linked in the way above. Here, we can simply pair each profile's centre, axis ratio and phi values.

This pairing should be done on a galaxy-by-galaxy basis. Provided the order of the galaxies supplied to a phase does not change (i.e the list of galaxi_models in lens_galaxies=[] and souce_galaxies=[]) then automatic prior linking works fine.

In fact, this may motivate a framework where the number of galaxy's does not change in a pipeline, unless an add_galaxy function is called. It would be worth discussing whether the downsides of this would conflict with model_mapper.

If two galaxy models are linked, where the previous galaxy model had aligned parameters or a parameter set to a constant, we need to define the default behaviour. Does the constant parameter become free? Do the align parameters stay aligned? In the pass priors, the current behaviour is that constants stay constant, linked parameters stay linked, etc, so I guess we would adopt this as default. Maybe we could have a boolean flag that switches all parameters to variable?

We've got a lot to work on, but with you currently working a lot on model mapper this may be something that you can start on (albeit, it well could not). I can write the function that pairs two models based on their mass / luminsoity.

**Comment by rhayes777** [comment]
linked_model_for_class creates a PriorModel wrapping the specified class with attributes from this instance. Priors can be overridden using keyword arguments. Any constructor arguments of the new class for which there is no attribute associated with this class and no keyword argument are created from config.

This means that priors with the same name can be matched in one line with the facility to override. There's also a boolean flag "make_constants_variable" which shifts the mean of priors in the new class to the value of associated constants in the original class.

**Comment by Jammy2211** [comment]
RIP this feature.
