### ISSUE TITLE
GetDist doesnt read paramnames file correct in phase 3 of x2_lens_galaxies howtolens

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#49]
Something is going wrong with getdit, whereby when it reads the multinest.paramnames file of the 2_x2_galaxies howtolens pipeline incorrectly.

I believe this is tied to whether getdist decides a parameter 'counts'. If it feels the samples of a parameter are too narrow or have too small a range it chooses to ignore it 0_0. This is a nightmare, and would mean we need to stop using getdist for parameter linking.

Ive put a raise error in non_linear.MultiNest.pdf, to check whether getdist has the same number of parameters as MultiNest, so that when this happens we know...

**Comment by rhayes777** [comment]
This must be related to the changes I made to multinest.paramnames.

Rich

**Comment by Jammy2211** [comment]
I dont think it is - Im pretty sure it doesnt even depend on the paramnames file.

GetDist randomly chooses to discard parameters if it thinks they're 'fixed', or their sampling is extremely narrow. For visualization, thats fair enough I guess, as it probably means it cant compute the PDF's it has to plot in the first place. But we're reliant on it for prior linking :(

**Comment by Jammy2211** [comment]
Fixed.
