### ISSUE TITLE
model info includes both dict and list of lens and source galaxies

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#50]
The model.info files now double output the source and lens galaxies in the priors, e.g.:

EllipticalSersic

lens_centre_0                           GaussianPrior, mean = 0.0, sigma = 1.0
lens_centre_1                           GaussianPrior, mean = 0.0, sigma = 1.0
lens_axis_ratio                         UniformPrior, lower_limit = 0.2, upper_limit = 1.0
lens_phi                                UniformPrior, lower_limit = 0.0, upper_limit = 180.0
lens_intensity                          UniformPrior, lower_limit = 0.0, upper_limit = 1.0
lens_effective_radius                   UniformPrior, lower_limit = 0.0, upper_limit = 4.0
lens_sersic_index                       UniformPrior, lower_limit = 0.8, upper_limit = 8.0

EllipticalSersic

lens_galaxies_centre_0                  GaussianPrior, mean = 0.0, sigma = 1.0
lens_galaxies_centre_1                  GaussianPrior, mean = 0.0, sigma = 1.0
lens_galaxies_axis_ratio                UniformPrior, lower_limit = 0.2, upper_limit = 1.0
lens_galaxies_phi                       UniformPrior, lower_limit = 0.0, upper_limit = 180.0
lens_galaxies_intensity                 UniformPrior, lower_limit = 0.0, upper_limit = 1.0
lens_galaxies_effective_radius          UniformPrior, lower_limit = 0.0, upper_limit = 4.0
lens_galaxies_sersic_index              UniformPrior, lower_limit = 0.8, upper_limit = 8.0

These are the same model, but being output twice.

I have fixed this by preventing 'lens_galaxies' and 'source_galaxies' from being output:

`    @property
    def info(self):
        """
        Use the priors that make up the model_mapper to generate information on each parameter of the overall model.

        This information is extracted from each priors *model_info* property.
        """
        info = []

        for prior_model_name, prior_model in self.flat_prior_model_tuples:

            # TODO : clean this up

            if 'lens_galaxies' not in prior_model_name and 'source_galaxies' not in prior_model_name:

                info.append(prior_model.cls.__name__ + '\n')

                prior_model_iterator = prior_model.prior_tuples + prior_model.constant_tuples

                for i, attribute_tuple in enumerate(prior_model_iterator):
                    attribute = attribute_tuple[1]

                    line = prior_model_name + '_' + attribute_tuple.name
                    info.append(line + ' ' * (60 - len(line)) + attribute.info)

                info.append('')

        return '\n'.join(info)`

This now produces the following output in model.info

EllipticalSersic

lens_centre_0                           GaussianPrior, mean = 0.0, sigma = 1.0
lens_centre_1                           GaussianPrior, mean = 0.0, sigma = 1.0
lens_axis_ratio                         UniformPrior, lower_limit = 0.2, upper_limit = 1.0
lens_phi                                UniformPrior, lower_limit = 0.0, upper_limit = 180.0
lens_intensity                          UniformPrior, lower_limit = 0.0, upper_limit = 1.0
lens_effective_radius                   UniformPrior, lower_limit = 0.0, upper_limit = 4.0
lens_sersic_index                       UniformPrior, lower_limit = 0.8, upper_limit = 8.0

This is good - previousouly this looked like

EllipticalSersic

lens_galaxies_lens_centre_0                           GaussianPrior, mean = 0.0, sigma = 1.0
lens_galaxies_lens_centre_1                           GaussianPrior, mean = 0.0, sigma = 1.0
lens_galaxies_lens_axis_ratio                         UniformPrior, lower_limit = 0.2, upper_limit = 1.0
lens_galaxies_lens_phi                                UniformPrior, lower_limit = 0.0, upper_limit = 180.0
lens_galaxies_lens_intensity                          UniformPrior, lower_limit = 0.0, upper_limit = 1.0
lens_galaxies_lens_effective_radius                   UniformPrior, lower_limit = 0.0, upper_limit = 4.0
lens_galaxies_lens_sersic_index                       UniformPrior, lower_limit = 0.8, upper_limit = 8.0

The issue is because im guessing we can do a better fix than an if loop

**Comment by rhayes777** [comment]
This issue was introduced by the named galaxy feature. I'm now filtering flat prior model tuples returned by the model mapper and used in model info to avoid duplication.
