### ISSUE TITLE
Pass a defaut mask (or mask function) to a pipeline

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#55]
Currently, a pipeline assumes a default mask function of 3.0", or uses the mask functions which are written in the pipeline. However, this means we cannot use a pipeline on 10 images, where each image has a specific mask tailored to its lens / source galaxies.

It would b e good if we could instead pass a default mask or default mask function to the pipeline when we run it - so that the same pipeline can be applied to a large set of images, but each one uses a specifically tailored mask.

**Comment by Jammy2211** [comment]
We should also be able to do this for the 'positions' input, which specificies the arc-second coordinates of the source galaxy's multiple images and ensures they trace close to one another during the lens modeling (to speed up the analysis by not analysing models which clearly dont trace close to one another)

**Comment by rhayes777** [comment]
I've made it so that a mask can optionally be passed in with an image when a pipeline is run. This mask is passed to each phase's run function and used as the default if not None.

**Comment by rhayes777** [comment]
Can we close this issue?
