### ISSUE TITLE
Improved package structure

### ISSUE THREAD

**Issue by rhayes777** [Jammy2211/PyAutoLens#58]
There are now 12 top level packages. It seems like those could grouped as two to four top level packages to keep things tidy. For instance, galaxy, imaging and profiles could be moved into a "model" package.

**Comment by Jammy2211** [comment]
We should coordinate this with PyAutoCTI.

We may also see some packages moved to separate projects and shared amongst different packages, like autofit will be.

**Comment by rhayes777** [comment]
Package structure looks better
