### ISSUE TITLE
remove 'lens_galaxies' and 'source_galaxies' from model.results

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#59]
an example model.results is:

Most likely model, Likelihood = 407202.40225935756

lens_galaxies_lens_0_axis_ratio                             0.9874494444113797
lens_galaxies_lens_0_phi                                    35.777835892818835
lens_galaxies_lens_1_axis_ratio                             0.8157185348065075
lens_galaxies_lens_1_phi                                    16.159869619849268
source_galaxies_source_0_axis_ratio                         0.4208820684855632
source_galaxies_source_0_phi                                64.87509808115392
source_galaxies_source_1_axis_ratio                         0.3748714657288664
source_galaxies_source_1_phi                                118.07383628337809
lens_galaxies_lens_0_einstein_radius                        1.3068638311593768
lens_galaxies_lens_1_einstein_radius                        0.4507796972088458
source_galaxies_source_0_effective_radius                   3.3606668082302447
source_galaxies_source_0_sersic_index                       2.793908773324765
source_galaxies_source_1_effective_radius                   0.4515732491147758
source_galaxies_source_1_sersic_index                       2.2009990003209126
source_galaxies_source_0_centre_0                           0.3216454170303999
source_galaxies_source_0_centre_1                           0.24691707328305945
source_galaxies_source_0_intensity                          2.192546132453832e-05
source_galaxies_source_1_centre_0                           -0.005651519040525119
source_galaxies_source_1_centre_1                           0.18749160049092783
source_galaxies_source_1_intensity                          0.00044165889697757386
lens_galaxies_lens_0_centre_0                               0.986947124221798
lens_galaxies_lens_0_centre_1                               0.48268756613348407
lens_galaxies_lens_1_centre_0                               -0.1675956799725098
lens_galaxies_lens_1_centre_1                               -0.5626954684520199

Constants

Can we remove the source_galaxies / lens_galaxies string bit? Seems uncessary.

**Comment by rhayes777** [comment]
Without using named galaxies you would end up with results that look like:

0_centre
0_centre

With no way to distinguish whether each of those two lines is the first source galaxy or the first lens galaxy.

**Comment by Jammy2211** [comment]
We're going in a direction where all objects will just be galaxies as we use a multi-plane ray tracer. Furthermore, model objects may also be planes, or other things, making the use of 'galaxies' not redundent.

So, Im closing this issue.
