### ISSUE TITLE
Custom Numba Decorator

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#69]
Depending on if we're using a super computer, we want two different numba decorators:

If on latptop:

@numba.jit(nopython=True, cache=True, parallel=False)

If on super computer:

@numba.jit(nopython=True, cache=False, parallel=True)

**Comment by rhayes777** [comment]
These fields can now be expressed in the [numba] section of general.ini. All @jit decorators now use the decorator defined in decorator util which wraps the numba decorator and loads values defined in general.ini as defaults.
