### ISSUE TITLE
Visualize sensitivity and substructure grid searches

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#70]
A (y,x) grid search gives us a 2 grid of likelihoods. We need to plot these likelihoods 'over' the observed image to show our sensitivity to a subhalo, or where the model places a subhalo.

**Comment by rhayes777** [comment]
The results object has a figure_of_merit_array attribute. Plotting this
should suffice?

**Comment by Jammy2211** [comment]
Is that available in both grid searches?

And are the grid-coordinates (e.g. y,x) available in a similar array?

**Comment by rhayes777** [comment]
Right now it's just the non classical grid search. Would be easy to
implement for classical grid search
