### ISSUE TITLE
Github Badges

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#76]
Yep.

**Comment by a-mere-peasant** [comment]
Hey, I've added a few badges and #134  should close it for now

**Comment by Jammy2211** [comment]
Hey, thanks!

Will look at this ASAP - very busy week with work so struggling to find time even to do something as simple as a pull request but will get this doe!

**Comment by a-mere-peasant** [comment]
Seems like the README has changed , could you tell me which badges to add ? Also mentioning @rhayes777 since he approved the first request

**Comment by Jammy2211** [comment]
We don't have a build server currently, so this limits us on some of the badges we can use.

From what I can see I would go for the following:

license badge.
arxiv badge linking to this paper (https://arxiv.org/abs/1708.07377)
code style - black

I'm honesty not sure what other badges are available,  are there any you think would be suited that are feasible currently?

p.s. sorry for never accepting your PR, got buried in other work!

**Comment by a-mere-peasant** [comment]
> We don't have a build server currently, so this limits us on some of the badges we can use.
> 
> From what I can see I would go for the following:
> 
> license badge.
> arxiv badge linking to this paper (https://arxiv.org/abs/1708.07377)
> code style - black
> 
I have added these in #152 
> I'm honesty not sure what other badges are available, are there any you think would be suited that are feasible currently?
> 
shields.io suggested the number of forks, stars and issues if any of those are to be added , there are badges for discord but not for slack but we can make some custom badges for those or anything else that might be required .There are version no badges for python and also badges like made with python ,or made with jupyter notebook if one of those might be suitable here.
 
Let me know if any of those or something custom is required 

> p.s. sorry for never accepting your PR, got buried in other work!

No problems :)

**Comment by Jammy2211** [comment]
I merged the PR, however the license badge is giving a red thing and point to an invalid link?

I would say go ahead and add the forks, stars + issues badges. A custom Slack badge would be great too!

**Comment by a-mere-peasant** [comment]
> I merged the PR, however the license badge is giving a red thing and point to an invalid link?
> 
Yeah I had noticed that but I thought there was just some temporary problem with that badge as it was showing correctly on sheilds.io , I'll just add a custom one

> I would say go ahead and add the forks, stars + issues badges. A custom Slack badge would be great too!

Ok, I'll add them as well

**Comment by a-mere-peasant** [comment]
I tried adding the forks stars and issues badges and there seems to be the same problem with them , it shows repo not found but their links are working , and for some reason the Slack badge is not rendering in proper color , it just renders as green for anything i put in the color field. Everything looks fine at shields.io , maybe there is some problem with how rst is parsed when they look for the repo, not sure what else could cause an issue.

here are how the badges render: https://github.com/a-mere-peasant/PyAutoLens/blob/master/README.rst

Should I leave them in as is ? I dont think there is a way to make custom dynamic badges for forks issues and stars, clicking on the badge still directs properly though .
