### ISSUE TITLE
Clean up manipulation of 1D deflection arrays to make 2d arays.

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#79]
In model.galaxy.util.galaxy_util -> deflections_of_galaxies_from_grid I do some weird stuff to make a 2d array of deflection angles from 1D values:

```
if galaxies:
        deflections = sum(map(lambda galaxy: galaxy.deflections_from_grid(grid), galaxies))
        if isinstance(grid, grids.SubGrid):
            return np.asarray([grid.sub_data_to_regular_data(deflections[:, 0]),
                               grid.sub_data_to_regular_data(deflections[:, 1])]).T
        return sum(map(lambda galaxy: galaxy.deflections_from_grid(grid), galaxies))
```

I am now doing the same thing iin the grid_interpolation function in data.array.grids (this function needs to return a 2D array of values if it decorates a deflections_from_grid function):

```
            if grid.interpolator is not None:
                values = func(profile, interpolator.interp_grid, *args, **kwargs)
                if values.ndim == 1:
                    return interpolator.interpolated_values_from_values(values=values)
                elif values.ndim == 2:
                    y_values = interpolator.interpolated_values_from_values(values=values[:,0])
                    x_values = interpolator.interpolated_values_from_values(values=values[:,1])
                    return np.asarray([y_values, x_values]).T
```

I've no doubt there is slightly neater syntax for this. Numpy Array slicing? vstack?

**Comment by rhayes777** [comment]
I've cleaned up the deflection angle code but the pattern of applying a function to different slices of an array doesn't seem too bad to me. If there were more repetition I would be inclined to refactor it but as it stands it seems that would just make the code less clear.
