### ISSUE TITLE
Variable PSF convolution kernel size to speed up convolution step

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#8]
The source PSF convolution routine currently goes to each pixel and computes the pixels within the mask that it needs to be blurred with during PSF convolution (it does this in 2D, but we agreed 1D would be more efficient). It does this by overlaying the kernel over the pixel and book-keeping all pixels within the mask and kernel.

However, a lot of the image-pixels in this mask will have essentially no source-light in them (the mask is big because of the lens galaxy's size). For these pixels, there is no need to use a big PSF kernel, as they really don't contain much information on the source. So, lets implement a routine which reduces the kernel size for image-pixels we know contain no source light. This should be straight-forward, as it should just come down to changing the kernel size input to each 'frames' you use to setup the convolution pre-analysis. 

Determining image pixels without source light is simple - we just look at the model of a previous run of the code (we do this anyway for the adaptive source reconstruction features).

**Comment by rhayes777** [comment]
The code was skipping the convolution of the kernel with zero values before. However, it was still adding an creating and adding an empty array for any non-zero value.

aa86ee8def097bd56eb17f402f75d450f11f4017 introduces a check for zero values so the convolution function is only called for non-zero values. 

A slight efficiency increase could be introduced if we had a set of known non-zero value indices.

The representation of a kernel and frame should also be examined as this could yield an efficiency increase for large frames that straddle the mask boundary.

**Comment by Jammy2211** [comment]
I'll look at the code this weekend. From what you've described, we'll still waste time on pixels which are outside the mask but overlap the kernel, which we should be able to ignore if we set the frames up correctly.

A variable kernel sizes nevertheless seems straight forward.

**Comment by rhayes777** [comment]
I’m going to make a dictionary representation of the frame and kernel which should solve this problem.

**Comment by rhayes777** [comment]
A dictionary is now used for the frame. That is, a kernel * value result is mapped onto the convolved vector using dictionary {k: v} where k is the kernel index and v the vector index, both in one dimension.

The kernel * value is still calculated for each element in the kernel as the result of this is reused. A further efficiency saving could be made by only calculating the convolved values as and when they're needed. I'm going to put off looking at this until we can profile a complete execution of the pipeline.
