### ISSUE TITLE
Unit test cache decorator on mass profiles

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#80]
I have added unit tests ensuring that when the profile has an interpolator decorator, it computes values corresponding to the interpolator.

It would be good if we could do this for the cache decorator as well, which I dont personally know how to test :P.

**Comment by rhayes777** [comment]
You mean testing that it gives the same result with and without the decorator?

**Comment by Jammy2211** [comment]
More that the cache is actually used, and that the calculation isnt repeated multiple times.

I commented out the cache decorators currently, as it felt like it was hugging memory on my laptop. I'm not sure that was actually due to the decorators though.

**Comment by rhayes777** [comment]
test_geometry_profiles.TestMemoize.test_get_from_cache already proves this by demonstrating that changes in the state of a class are not reflected in the results of repeated function calls.
