### ISSUE TITLE
Include general results for all lenses in a folder

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#86]
Currently, our directory structure goes data_type > data_name > pipeline.

We want general results files that describe the results of applying a pipeline to a large set of data. i.e., we want a model.results file in the  data_type folder, that lists all of the results for all data_names and all pipelines applied to it. 

I think it may be more natural that we change the directory structure to 

pipeline > data_type > data name

So that one can see the results of a pipeline applied to all data. I guess it depends on what works better in the context of the data-base for looking up large sets of results.

**Comment by rhayes777** [comment]
Alongside this it may be useful to look at the automation and collation scripts that we discussed this week.

**Comment by Jammy2211** [comment]
Yeah, this is definitely the most important functionality to get up soon.

I think there is no harm in keeeping the currently directory structure. In the data_type folder we could have a results file for each pipeline, that shows the results of that pipeline applied to all data_names. In terms of navigation, the current directory strucutre is more intuitive.

I am going to be adding 'output' modules that output the results of profiles, galaxies, pllanes, tracers etc, to a file, which will written in a style mirroring the plotter modulels.

**Comment by rhayes777** [comment]
If the collation tools work well then it shouldn’t matter too much which way we order the directories.

**Comment by Jammy2211** [comment]
The aggregaor is addressing this issue.
