### ISSUE TITLE
Should we require that all galaxies have a redshift

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#87]
I am toying with the idea that we require that all galaxies have a redshift, and do not allow them to assume their current default value of None.

The motivation for this is that by not requiring the user to specify galaxy redshifts, the following problems arise:

1) It is unambiguous if the results of a model can be output in physical units, via conversion using a cosmology. If we required galaxy redshifts, we could assume fiducial values (e.g. z_lens = 0.5, z_src=1.0) for systems where the redshifts are unknown and not change the code behaviour.

2) By having it be possible a galaxy has no redshift, it is leading to a lot of extra code that checks if this is the case and changes behaviour as appropriate. This would allow us to trim some code.

3) It is less explicit to the user 'hiding' redshift as we do now.

The main downside of requiring redshift is that it requires more input from the user, especially when constructing a TracerImageSourcePlanes where you dont really want to be thinking about galaxy redshifts.

**Comment by rhayes777** [comment]
We could implicitly set the redshift of galaxies in lens source phases and then throw an exception if redshift is not set in more general phases

**Comment by Jammy2211** [comment]
The redshift of a Galaxy and GalaxyModel are now required. This will enable us to refactor the Plane and Tracer classes.
