### ISSUE TITLE
Extract list of model mappers / NLOs from aggregator

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#88]
The aggregator looks great, and is a powerful tool for summarizing results. From what we have already, we could use it to filter through results and get parameter estimates + errors based on input variable names, etc.

Whilst we want to use the aggregator to directly extract parameter estimates / values, I think we'd also benefit from setting up the NLO used in a the phase of a pipeline. If we have the NLO, we then have access to all results, with the correct model mapper required to map them to an instance of a physical model.

Once I have a NLO, I can then access every MultiNest sample, including its weighted likelihood value. This will allow me to infer integrated quantities from the model in the statistically 'correct' way, e.g. computing the mass as the weighted average over al MultiNest samples. Some of these things will be output during the analysis in a summary file, but having access to all model results in this way will enable more intricate statistical analyses.

**Comment by Jammy2211** [comment]
To setup the NLO in a way that has exactly the same mapper as was used in the pipeline may be tricky - the pass priors functions swap round the prior ids in a difficult to reproduce way.

However, I think the order of the priors in the 'model.info' reflects the ids in the model mapper, and the priors in the 'model.info' file certainly reflect the correct priors for the mapper that is used to setup the NLO. If not, we can generate some more metadata.

**Comment by rhayes777** [comment]
The aggregator module can now be used to extract optimizers recursively from a given directory with optional filters.

Basic usage:
`
from autolens import aggregator
agg = aggregator.Aggregator("test/unit/test_files/aggregator")
optimizers = agg.optimizers_with()
print(optimizers[0].variable.info)
`

This will only work on new runs as a pickle file is now generated by the pipeline module for each phase.
