### ISSUE TITLE
Implemented Minimum Radial Coordinate 

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoLens#89]
There were issues where coordinates at or very close to (0.0, 0.0) were breaking the numerical integration required to compute deflection angles. Therefore, I have written a wrapper to the grid_from_ methods in light / mass profiles which relocates all coordinates within a threshold value from (0.0, 0.0) to that value, radially. This is implemented and tested, and all from_grid methods now have an input parameter grid_radial_minimum.

This was for the subhalo challenge, and the isothermal / power mass profiles assume default values of 1.0e-8 currently so that my models on Cosma use this feature.

However, I have not yet implemented it fully in the 'system' as I am not sure the best way to. Ideally, we will have a config file specifying these values for every light and mass profile, and these values will be loaded before a pipeline runs and used. However, I am unsure where in the code we read this config file:

-  If we do it in the profile's constructor, does that mean we'll have a lot of IO for every time we create a profile during the MultiNest seach? 

- If we do it in phase.py, do we need to pass this long list of values through the tracer, plane and galaxy modules when we call a from_grid method?

Over to you...

**Comment by rhayes777** [comment]
This can now be done by modifying the radial_minimum.ini file. I've put a set of defaults in there which I will leave you to modify.
